/**
 * AUTO-GENERATED by scripts/import-scl-packs.mjs — do not edit by hand.
 * Re-run the importer after Neil drops updated SCL packs.
 */
import type { BiomarkerConfig } from './config'
import { registerBiomarkerConfig } from './config'
import { registerClaimSource } from './csl'

import APOB_TOTAL_CLAIMS from './csl-data/apob-total.json'
import HBA1C_CLAIMS from './csl-data/hba1c.json'
import LDL_C_CLAIMS from './csl-data/ldl-c.json'
import HDL_C_CLAIMS from './csl-data/hdl-c.json'
import TRIGLYCERIDES_CLAIMS from './csl-data/triglycerides.json'
import HS_CRP_CLAIMS from './csl-data/hs-crp.json'
import NON_HDL_C_CLAIMS from './csl-data/non-hdl-c.json'
import TOTAL_CHOLESTEROL_CLAIMS from './csl-data/total-cholesterol.json'
import FASTING_GLUCOSE_CLAIMS from './csl-data/fasting-glucose.json'
import FERRITIN_CLAIMS from './csl-data/ferritin.json'
import VITAMIN_D_CLAIMS from './csl-data/vitamin-d.json'
import VITAMIN_B12_CLAIMS from './csl-data/vitamin-b12.json'
import FOLATE_CLAIMS from './csl-data/folate.json'
import ALT_CLAIMS from './csl-data/alt.json'
import AST_CLAIMS from './csl-data/ast.json'
import EGFR_CLAIMS from './csl-data/egfr.json'
import TSH_CLAIMS from './csl-data/tsh.json'
import FREE_T4_CLAIMS from './csl-data/free-t4.json'
import HAEMOGLOBIN_CLAIMS from './csl-data/haemoglobin.json'
import WBC_CLAIMS from './csl-data/wbc.json'
import GGT_CLAIMS from './csl-data/ggt.json'
import ALP_CLAIMS from './csl-data/alp.json'
import BILIRUBIN_CLAIMS from './csl-data/bilirubin.json'
import ALBUMIN_CLAIMS from './csl-data/albumin.json'

export const SCL_REGISTRY = [
  {
    "scl_id": "SCL-001",
    "analyte": "APOB_TOTAL",
    "display_name": "Apolipoprotein B",
    "aliases": [
      "ApoB",
      "Apolipoprotein B",
      "APOB",
      "Apo B"
    ],
    "unit": "mg/dL",
    "conversions": {
      "mg/dL": 1,
      "g/L": 100,
      "mg/L": 0.1
    },
    "direction": "LOWER_BETTER",
    "threshold_claim": "BIOSENSE_APOB_TOTAL_THRESHOLD_SET",
    "companion_threshold_set": "BIOSENSE_LDLC_THRESHOLD_SET",
    "config_version": "APOB_TOTAL_CONFIG@1.0.0",
    "banding_anchored": true,
    "band_count": 5,
    "source_date": "2026-07-26"
  },
  {
    "scl_id": "SCL-002",
    "analyte": "HBA1C",
    "display_name": "HbA1c",
    "aliases": [
      "HbA1c",
      "A1c",
      "Glycated Haemoglobin",
      "glycohaemoglobin"
    ],
    "unit": "%",
    "conversions": {
      "%": 1
    },
    "direction": "LOWER_BETTER",
    "threshold_claim": "BIOSENSE_HBA1C_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "HBA1C_CONFIG@1.0.0",
    "banding_anchored": true,
    "band_count": 6,
    "source_date": "2026-07-30"
  },
  {
    "scl_id": "SCL-003",
    "analyte": "LDL_C",
    "display_name": "LDL Cholesterol",
    "aliases": [
      "LDL-C",
      "LDL C",
      "LDL Cholesterol",
      "LDL"
    ],
    "unit": "mg/dL",
    "conversions": {
      "mg/dL": 1,
      "mmol/L": 38.67
    },
    "direction": "LOWER_BETTER",
    "threshold_claim": "BIOSENSE_LDL_C_THRESHOLD_SET",
    "companion_threshold_set": "BIOSENSE_APOB_THRESHOLD_SET",
    "config_version": "LDL_C_CONFIG@1.0.0",
    "banding_anchored": true,
    "band_count": 5,
    "source_date": "2026-07-31"
  },
  {
    "scl_id": "SCL-004",
    "analyte": "HDL_C",
    "display_name": "HDL Cholesterol",
    "aliases": [
      "HDL-C",
      "HDL",
      "HDL Cholesterol"
    ],
    "unit": "mg/dL",
    "conversions": {
      "mg/dL": 1,
      "mmol/L": 38.67
    },
    "direction": "HIGHER_BETTER",
    "threshold_claim": "BIOSENSE_HDL_C_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "HDL_C_CONFIG@1.0.0",
    "banding_anchored": false,
    "band_count": 10,
    "source_date": "2026-07-31"
  },
  {
    "scl_id": "SCL-005",
    "analyte": "TRIGLYCERIDES",
    "display_name": "Triglycerides",
    "aliases": [
      "Triglycerides",
      "TG",
      "Trigs"
    ],
    "unit": "mg/dL",
    "conversions": {
      "mg/dL": 1,
      "mmol/L": 88.57
    },
    "direction": "LOWER_BETTER",
    "threshold_claim": "BIOSENSE_TRIGLYCERIDES_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "TRIGLYCERIDES_CONFIG@1.0.0",
    "banding_anchored": true,
    "band_count": 9,
    "source_date": "2026-07-31"
  },
  {
    "scl_id": "SCL-006",
    "analyte": "HS_CRP",
    "display_name": "hs-CRP",
    "aliases": [
      "hs-CRP",
      "hsCRP",
      "high-sensitivity CRP",
      "CRP"
    ],
    "unit": "mg/L",
    "conversions": {
      "mg/L": 1
    },
    "direction": "LOWER_BETTER",
    "threshold_claim": "BIOSENSE_HS_CRP_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "HS_CRP_CONFIG@1.0.0",
    "banding_anchored": false,
    "band_count": 3,
    "source_date": "2026-07-31"
  },
  {
    "scl_id": "SCL-007",
    "analyte": "NON_HDL_C",
    "display_name": "Non-HDL Cholesterol",
    "aliases": [
      "Non-HDL-C",
      "non-HDL",
      "Non HDL-C"
    ],
    "unit": "mg/dL",
    "conversions": {
      "mg/dL": 1,
      "mmol/L": 38.67
    },
    "direction": "LOWER_BETTER",
    "threshold_claim": "BIOSENSE_NON_HDL_C_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "NON_HDL_C_CONFIG@1.0.0",
    "banding_anchored": false,
    "band_count": 0,
    "source_date": "2026-07-31"
  },
  {
    "scl_id": "SCL-008",
    "analyte": "TOTAL_CHOLESTEROL",
    "display_name": "Total Cholesterol",
    "aliases": [
      "Total Cholesterol",
      "TC",
      "Cholesterol"
    ],
    "unit": "mg/dL",
    "conversions": {
      "mg/dL": 1,
      "mmol/L": 38.67
    },
    "direction": "LOWER_BETTER",
    "threshold_claim": "BIOSENSE_TOTAL_CHOLESTEROL_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "TOTAL_CHOLESTEROL_CONFIG@1.0.0",
    "banding_anchored": false,
    "band_count": 3,
    "source_date": "2026-07-31"
  },
  {
    "scl_id": "SCL-009",
    "analyte": "FASTING_GLUCOSE",
    "display_name": "Fasting Glucose",
    "aliases": [
      "Fasting Glucose",
      "Glucose",
      "FPG",
      "FBG"
    ],
    "unit": "mg/dL",
    "conversions": {
      "mg/dL": 1,
      "mmol/L": 18.018
    },
    "direction": "LOWER_BETTER",
    "threshold_claim": "BIOSENSE_FASTING_GLUCOSE_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "FASTING_GLUCOSE_CONFIG@1.0.0",
    "banding_anchored": true,
    "band_count": 6,
    "source_date": "2026-07-31"
  },
  {
    "scl_id": "SCL-010",
    "analyte": "FERRITIN",
    "display_name": "Ferritin",
    "aliases": [
      "Ferritin",
      "serum ferritin"
    ],
    "unit": "µg/L",
    "conversions": {
      "µg/L": 1,
      "ng/mL": 1,
      "ug/L": 1
    },
    "direction": "TARGET_BAND",
    "threshold_claim": "BIOSENSE_FERRITIN_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "FERRITIN_CONFIG@1.0.0",
    "banding_anchored": true,
    "band_count": 10,
    "source_date": "2026-07-31"
  },
  {
    "scl_id": "SCL-011",
    "analyte": "VITAMIN_D",
    "display_name": "Vitamin D (25-OH)",
    "aliases": [
      "Vitamin D",
      "25(OH)D",
      "25-OH Vitamin D",
      "calcidiol"
    ],
    "unit": "ng/mL",
    "conversions": {
      "ng/mL": 1,
      "nmol/L": 0.40064102564102566
    },
    "direction": "TARGET_BAND",
    "threshold_claim": "BIOSENSE_VITAMIN_D_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "VITAMIN_D_CONFIG@1.0.0",
    "banding_anchored": true,
    "band_count": 2,
    "source_date": "2026-07-31"
  },
  {
    "scl_id": "SCL-012",
    "analyte": "VITAMIN_B12",
    "display_name": "Vitamin B12",
    "aliases": [
      "Vitamin B12",
      "B12",
      "Cobalamin"
    ],
    "unit": "pg/mL",
    "conversions": {
      "pg/mL": 1,
      "ng/L": 1,
      "pmol/L": 1.355
    },
    "direction": "TARGET_BAND",
    "threshold_claim": "BIOSENSE_VITAMIN_B12_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "VITAMIN_B12_CONFIG@1.0.0",
    "banding_anchored": true,
    "band_count": 2,
    "source_date": "2026-08-01"
  },
  {
    "scl_id": "SCL-013",
    "analyte": "FOLATE",
    "display_name": "Folate",
    "aliases": [
      "Folate",
      "Folic acid",
      "Serum folate"
    ],
    "unit": "ng/mL",
    "conversions": {
      "ng/mL": 1,
      "nmol/L": 0.44130626654898497
    },
    "direction": "TARGET_BAND",
    "threshold_claim": "BIOSENSE_FOLATE_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "FOLATE_CONFIG@1.0.0",
    "banding_anchored": true,
    "band_count": 2,
    "source_date": "2026-08-01"
  },
  {
    "scl_id": "SCL-014",
    "analyte": "ALT",
    "display_name": "ALT",
    "aliases": [
      "ALT",
      "Alanine aminotransferase",
      "SGPT"
    ],
    "unit": "U/L",
    "conversions": {
      "U/L": 1,
      "IU/L": 1
    },
    "direction": "LOWER_BETTER",
    "threshold_claim": "BIOSENSE_ALT_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "ALT_CONFIG@1.0.0",
    "banding_anchored": false,
    "band_count": 1,
    "source_date": "2026-08-01"
  },
  {
    "scl_id": "SCL-015",
    "analyte": "AST",
    "display_name": "AST",
    "aliases": [
      "AST",
      "Aspartate aminotransferase",
      "SGOT"
    ],
    "unit": "U/L",
    "conversions": {
      "U/L": 1,
      "IU/L": 1
    },
    "direction": "LOWER_BETTER",
    "threshold_claim": "BIOSENSE_AST_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "AST_CONFIG@1.0.0",
    "banding_anchored": false,
    "band_count": 2,
    "source_date": "2026-08-01"
  },
  {
    "scl_id": "SCL-016",
    "analyte": "EGFR",
    "display_name": "eGFR",
    "aliases": [
      "eGFR",
      "Estimated GFR",
      "Creatinine eGFR"
    ],
    "unit": "mL/min/1.73m²",
    "conversions": {
      "mL/min/1.73m²": 1,
      "mL/min/1.73m2": 1
    },
    "direction": "HIGHER_BETTER",
    "threshold_claim": "BIOSENSE_EGFR_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "EGFR_CONFIG@1.0.0",
    "banding_anchored": true,
    "band_count": 0,
    "source_date": "2026-08-01"
  },
  {
    "scl_id": "SCL-017",
    "analyte": "TSH",
    "display_name": "TSH",
    "aliases": [
      "TSH",
      "Thyroid Stimulating Hormone",
      "thyrotropin"
    ],
    "unit": "mIU/L",
    "conversions": {
      "mIU/L": 1,
      "µIU/mL": 1,
      "mU/L": 1
    },
    "direction": "TARGET_BAND",
    "threshold_claim": "BIOSENSE_TSH_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "TSH_CONFIG@1.0.0",
    "banding_anchored": true,
    "band_count": 2,
    "source_date": "2026-08-01"
  },
  {
    "scl_id": "SCL-018",
    "analyte": "FREE_T4",
    "display_name": "Free T4",
    "aliases": [
      "Free T4",
      "FT4",
      "free thyroxine"
    ],
    "unit": "ng/dL",
    "conversions": {
      "ng/dL": 1,
      "pmol/L": 0.07770007770007771
    },
    "direction": "TARGET_BAND",
    "threshold_claim": "BIOSENSE_FREE_T4_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "FREE_T4_CONFIG@1.0.0",
    "banding_anchored": false,
    "band_count": 0,
    "source_date": "2026-08-01"
  },
  {
    "scl_id": "SCL-019",
    "analyte": "HAEMOGLOBIN",
    "display_name": "Haemoglobin",
    "aliases": [
      "Haemoglobin",
      "Hemoglobin",
      "Hb",
      "Hgb"
    ],
    "unit": "g/dL",
    "conversions": {
      "g/dL": 1,
      "g/L": 0.1
    },
    "direction": "TARGET_BAND",
    "threshold_claim": "BIOSENSE_HAEMOGLOBIN_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "HAEMOGLOBIN_CONFIG@1.0.0",
    "banding_anchored": false,
    "band_count": 0,
    "source_date": "2026-08-01"
  },
  {
    "scl_id": "SCL-020",
    "analyte": "WBC",
    "display_name": "White Blood Cell Count",
    "aliases": [
      "WBC",
      "White cell count",
      "Leukocytes"
    ],
    "unit": "×10⁹/L",
    "conversions": {
      "×10⁹/L": 1,
      "x10^9/L": 1,
      "/µL": 0.001
    },
    "direction": "TARGET_BAND",
    "threshold_claim": "BIOSENSE_WBC_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "WBC_CONFIG@1.0.0",
    "banding_anchored": true,
    "band_count": 2,
    "source_date": "2026-08-01"
  },
  {
    "scl_id": "SCL-021",
    "analyte": "GGT",
    "display_name": "GGT",
    "aliases": [
      "GGT",
      "Gamma-GT",
      "γ-GT"
    ],
    "unit": "U/L",
    "conversions": {
      "U/L": 1,
      "IU/L": 1
    },
    "direction": "LOWER_BETTER",
    "threshold_claim": "BIOSENSE_GGT_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "GGT_CONFIG@1.0.0",
    "banding_anchored": false,
    "band_count": 0,
    "source_date": "2026-08-01"
  },
  {
    "scl_id": "SCL-022",
    "analyte": "ALP",
    "display_name": "Alkaline Phosphatase",
    "aliases": [
      "ALP",
      "Alkaline Phosphatase"
    ],
    "unit": "U/L",
    "conversions": {
      "U/L": 1,
      "IU/L": 1
    },
    "direction": "TARGET_BAND",
    "threshold_claim": "BIOSENSE_ALP_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "ALP_CONFIG@1.0.0",
    "banding_anchored": true,
    "band_count": 1,
    "source_date": "2026-08-01"
  },
  {
    "scl_id": "SCL-023",
    "analyte": "BILIRUBIN",
    "display_name": "Bilirubin",
    "aliases": [
      "Bilirubin",
      "Total bilirubin"
    ],
    "unit": "mg/dL",
    "conversions": {
      "mg/dL": 1,
      "µmol/L": 0.05847953216374269
    },
    "direction": "LOWER_BETTER",
    "threshold_claim": "BIOSENSE_BILIRUBIN_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "BILIRUBIN_CONFIG@1.0.0",
    "banding_anchored": false,
    "band_count": 2,
    "source_date": "2026-08-01"
  },
  {
    "scl_id": "SCL-024",
    "analyte": "ALBUMIN",
    "display_name": "Albumin",
    "aliases": [
      "Albumin",
      "Serum albumin"
    ],
    "unit": "g/dL",
    "conversions": {
      "g/dL": 1,
      "g/L": 0.1
    },
    "direction": "HIGHER_BETTER",
    "threshold_claim": "BIOSENSE_ALBUMIN_THRESHOLD_SET",
    "companion_threshold_set": null,
    "config_version": "ALBUMIN_CONFIG@1.0.0",
    "banding_anchored": false,
    "band_count": 1,
    "source_date": "2026-08-01"
  }
] as const

export function registerAllSclPacks(): void {
  registerClaimSource('csl-data/apob-total.json', APOB_TOTAL_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'APOB_TOTAL',
    display_name: 'Apolipoprotein B',
    ingestion: {
      unit_canonical: 'mg/dL',
      conversions: {"mg/dL":1,"g/L":100,"mg/L":0.1},
      aliases: ["ApoB","Apolipoprotein B","APOB","Apo B"],
      scope_population: 'ADULT',
    },
    direction: 'LOWER_BETTER',
    cumulative_exposure_relevant: true,
    constants: {
      threshold_set: 'BIOSENSE_APOB_THRESHOLD_SET',
      score_gap_scale: 'APOB_SCORE_GAP_SCALE',
      significant_change_threshold: 'APOB_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'APOB_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'APOB_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'APOB_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'APOB_FH_PATTERN_THRESHOLD',
      companion_threshold_set: 'BIOSENSE_LDLC_THRESHOLD_SET',
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'APOB_TOTAL_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/hba1c.json', HBA1C_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'HBA1C',
    display_name: 'HbA1c',
    ingestion: {
      unit_canonical: '%',
      conversions: {"%":1},
      aliases: ["HbA1c","A1c","Glycated Haemoglobin","glycohaemoglobin"],
      scope_population: 'ADULT',
    },
    direction: 'LOWER_BETTER',
    cumulative_exposure_relevant: true,
    constants: {
      threshold_set: 'BIOSENSE_HBA1C_THRESHOLD_SET',
      score_gap_scale: 'HBA1C_SCORE_GAP_SCALE',
      significant_change_threshold: 'HBA1C_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'HBA1C_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'HBA1C_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'HBA1C_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'HBA1C_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'HBA1C_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/ldl-c.json', LDL_C_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'LDL_C',
    display_name: 'LDL Cholesterol',
    ingestion: {
      unit_canonical: 'mg/dL',
      conversions: {"mg/dL":1,"mmol/L":38.67},
      aliases: ["LDL-C","LDL C","LDL Cholesterol","LDL"],
      scope_population: 'ADULT',
    },
    direction: 'LOWER_BETTER',
    cumulative_exposure_relevant: true,
    constants: {
      threshold_set: 'BIOSENSE_LDL_C_THRESHOLD_SET',
      score_gap_scale: 'LDL_C_SCORE_GAP_SCALE',
      significant_change_threshold: 'LDL_C_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'LDL_C_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'LDL_C_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'LDL_C_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'LDL_C_FH_PATTERN_THRESHOLD',
      companion_threshold_set: 'BIOSENSE_APOB_THRESHOLD_SET',
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'LDL_C_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/hdl-c.json', HDL_C_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'HDL_C',
    display_name: 'HDL Cholesterol',
    ingestion: {
      unit_canonical: 'mg/dL',
      conversions: {"mg/dL":1,"mmol/L":38.67},
      aliases: ["HDL-C","HDL","HDL Cholesterol"],
      scope_population: 'ADULT',
    },
    direction: 'TARGET_BAND',
    cumulative_exposure_relevant: false,
    constants: {
      threshold_set: 'BIOSENSE_HDL_C_THRESHOLD_SET',
      score_gap_scale: 'HDL_C_SCORE_GAP_SCALE',
      significant_change_threshold: 'HDL_C_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'HDL_C_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'HDL_C_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'HDL_C_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'HDL_C_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'HDL_C_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/triglycerides.json', TRIGLYCERIDES_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'TRIGLYCERIDES',
    display_name: 'Triglycerides',
    ingestion: {
      unit_canonical: 'mg/dL',
      conversions: {"mg/dL":1,"mmol/L":88.57},
      aliases: ["Triglycerides","TG","Trigs"],
      scope_population: 'ADULT',
    },
    direction: 'LOWER_BETTER',
    cumulative_exposure_relevant: true,
    constants: {
      threshold_set: 'BIOSENSE_TRIGLYCERIDES_THRESHOLD_SET',
      score_gap_scale: 'TRIGLYCERIDES_SCORE_GAP_SCALE',
      significant_change_threshold: 'TRIGLYCERIDES_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'TRIGLYCERIDES_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'TRIGLYCERIDES_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'TRIGLYCERIDES_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'TRIGLYCERIDES_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'TRIGLYCERIDES_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/hs-crp.json', HS_CRP_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'HS_CRP',
    display_name: 'hs-CRP',
    ingestion: {
      unit_canonical: 'mg/L',
      conversions: {"mg/L":1},
      aliases: ["hs-CRP","hsCRP","high-sensitivity CRP","CRP"],
      scope_population: 'ADULT',
    },
    direction: 'LOWER_BETTER',
    cumulative_exposure_relevant: true,
    constants: {
      threshold_set: 'BIOSENSE_HS_CRP_THRESHOLD_SET',
      score_gap_scale: 'HS_CRP_SCORE_GAP_SCALE',
      significant_change_threshold: 'HS_CRP_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'HS_CRP_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'HS_CRP_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'HS_CRP_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'HS_CRP_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'HS_CRP_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/non-hdl-c.json', NON_HDL_C_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'NON_HDL_C',
    display_name: 'Non-HDL Cholesterol',
    ingestion: {
      unit_canonical: 'mg/dL',
      conversions: {"mg/dL":1,"mmol/L":38.67},
      aliases: ["Non-HDL-C","non-HDL","Non HDL-C"],
      scope_population: 'ADULT',
    },
    direction: 'LOWER_BETTER',
    cumulative_exposure_relevant: true,
    constants: {
      threshold_set: 'BIOSENSE_NON_HDL_C_THRESHOLD_SET',
      score_gap_scale: 'NON_HDL_C_SCORE_GAP_SCALE',
      significant_change_threshold: 'NON_HDL_C_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'NON_HDL_C_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'NON_HDL_C_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'NON_HDL_C_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'NON_HDL_C_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'NON_HDL_C_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/total-cholesterol.json', TOTAL_CHOLESTEROL_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'TOTAL_CHOLESTEROL',
    display_name: 'Total Cholesterol',
    ingestion: {
      unit_canonical: 'mg/dL',
      conversions: {"mg/dL":1,"mmol/L":38.67},
      aliases: ["Total Cholesterol","TC","Cholesterol"],
      scope_population: 'ADULT',
    },
    direction: 'LOWER_BETTER',
    cumulative_exposure_relevant: true,
    constants: {
      threshold_set: 'BIOSENSE_TOTAL_CHOLESTEROL_THRESHOLD_SET',
      score_gap_scale: 'TOTAL_CHOLESTEROL_SCORE_GAP_SCALE',
      significant_change_threshold: 'TOTAL_CHOLESTEROL_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'TOTAL_CHOLESTEROL_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'TOTAL_CHOLESTEROL_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'TOTAL_CHOLESTEROL_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'TOTAL_CHOLESTEROL_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'TOTAL_CHOLESTEROL_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/fasting-glucose.json', FASTING_GLUCOSE_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'FASTING_GLUCOSE',
    display_name: 'Fasting Glucose',
    ingestion: {
      unit_canonical: 'mg/dL',
      conversions: {"mg/dL":1,"mmol/L":18.018},
      aliases: ["Fasting Glucose","Glucose","FPG","FBG"],
      scope_population: 'ADULT',
    },
    direction: 'LOWER_BETTER',
    cumulative_exposure_relevant: true,
    constants: {
      threshold_set: 'BIOSENSE_FASTING_GLUCOSE_THRESHOLD_SET',
      score_gap_scale: 'FASTING_GLUCOSE_SCORE_GAP_SCALE',
      significant_change_threshold: 'FASTING_GLUCOSE_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'FASTING_GLUCOSE_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'FASTING_GLUCOSE_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'FASTING_GLUCOSE_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'FASTING_GLUCOSE_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'FASTING_GLUCOSE_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/ferritin.json', FERRITIN_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'FERRITIN',
    display_name: 'Ferritin',
    ingestion: {
      unit_canonical: 'µg/L',
      conversions: {"µg/L":1,"ng/mL":1,"ug/L":1},
      aliases: ["Ferritin","serum ferritin"],
      scope_population: 'ADULT',
    },
    direction: 'TARGET_BAND',
    cumulative_exposure_relevant: false,
    constants: {
      threshold_set: 'BIOSENSE_FERRITIN_THRESHOLD_SET',
      score_gap_scale: 'FERRITIN_SCORE_GAP_SCALE',
      significant_change_threshold: 'FERRITIN_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'FERRITIN_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'FERRITIN_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'FERRITIN_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'FERRITIN_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'FERRITIN_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/vitamin-d.json', VITAMIN_D_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'VITAMIN_D',
    display_name: 'Vitamin D (25-OH)',
    ingestion: {
      unit_canonical: 'ng/mL',
      conversions: {"ng/mL":1,"nmol/L":0.40064102564102566},
      aliases: ["Vitamin D","25(OH)D","25-OH Vitamin D","calcidiol"],
      scope_population: 'ADULT',
    },
    direction: 'TARGET_BAND',
    cumulative_exposure_relevant: false,
    constants: {
      threshold_set: 'BIOSENSE_VITAMIN_D_THRESHOLD_SET',
      score_gap_scale: 'VITAMIN_D_SCORE_GAP_SCALE',
      significant_change_threshold: 'VITAMIN_D_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'VITAMIN_D_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'VITAMIN_D_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'VITAMIN_D_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'VITAMIN_D_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'VITAMIN_D_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/vitamin-b12.json', VITAMIN_B12_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'VITAMIN_B12',
    display_name: 'Vitamin B12',
    ingestion: {
      unit_canonical: 'pg/mL',
      conversions: {"pg/mL":1,"ng/L":1,"pmol/L":1.355},
      aliases: ["Vitamin B12","B12","Cobalamin"],
      scope_population: 'ADULT',
    },
    direction: 'TARGET_BAND',
    cumulative_exposure_relevant: false,
    constants: {
      threshold_set: 'BIOSENSE_VITAMIN_B12_THRESHOLD_SET',
      score_gap_scale: 'VITAMIN_B12_SCORE_GAP_SCALE',
      significant_change_threshold: 'VITAMIN_B12_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'VITAMIN_B12_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'VITAMIN_B12_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'VITAMIN_B12_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'VITAMIN_B12_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'VITAMIN_B12_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/folate.json', FOLATE_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'FOLATE',
    display_name: 'Folate',
    ingestion: {
      unit_canonical: 'ng/mL',
      conversions: {"ng/mL":1,"nmol/L":0.44130626654898497},
      aliases: ["Folate","Folic acid","Serum folate"],
      scope_population: 'ADULT',
    },
    direction: 'TARGET_BAND',
    cumulative_exposure_relevant: false,
    constants: {
      threshold_set: 'BIOSENSE_FOLATE_THRESHOLD_SET',
      score_gap_scale: 'FOLATE_SCORE_GAP_SCALE',
      significant_change_threshold: 'FOLATE_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'FOLATE_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'FOLATE_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'FOLATE_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'FOLATE_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'FOLATE_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/alt.json', ALT_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'ALT',
    display_name: 'ALT',
    ingestion: {
      unit_canonical: 'U/L',
      conversions: {"U/L":1,"IU/L":1},
      aliases: ["ALT","Alanine aminotransferase","SGPT"],
      scope_population: 'ADULT',
    },
    direction: 'LOWER_BETTER',
    cumulative_exposure_relevant: true,
    constants: {
      threshold_set: 'BIOSENSE_ALT_THRESHOLD_SET',
      score_gap_scale: 'ALT_SCORE_GAP_SCALE',
      significant_change_threshold: 'ALT_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'ALT_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'ALT_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'ALT_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'ALT_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'ALT_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/ast.json', AST_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'AST',
    display_name: 'AST',
    ingestion: {
      unit_canonical: 'U/L',
      conversions: {"U/L":1,"IU/L":1},
      aliases: ["AST","Aspartate aminotransferase","SGOT"],
      scope_population: 'ADULT',
    },
    direction: 'LOWER_BETTER',
    cumulative_exposure_relevant: true,
    constants: {
      threshold_set: 'BIOSENSE_AST_THRESHOLD_SET',
      score_gap_scale: 'AST_SCORE_GAP_SCALE',
      significant_change_threshold: 'AST_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'AST_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'AST_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'AST_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'AST_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'AST_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/egfr.json', EGFR_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'EGFR',
    display_name: 'eGFR',
    ingestion: {
      unit_canonical: 'mL/min/1.73m²',
      conversions: {"mL/min/1.73m²":1,"mL/min/1.73m2":1},
      aliases: ["eGFR","Estimated GFR","Creatinine eGFR"],
      scope_population: 'ADULT',
    },
    direction: 'HIGHER_BETTER',
    cumulative_exposure_relevant: false,
    constants: {
      threshold_set: 'BIOSENSE_EGFR_THRESHOLD_SET',
      score_gap_scale: 'EGFR_SCORE_GAP_SCALE',
      significant_change_threshold: 'EGFR_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'EGFR_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'EGFR_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'EGFR_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'EGFR_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'EGFR_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/tsh.json', TSH_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'TSH',
    display_name: 'TSH',
    ingestion: {
      unit_canonical: 'mIU/L',
      conversions: {"mIU/L":1,"µIU/mL":1,"mU/L":1},
      aliases: ["TSH","Thyroid Stimulating Hormone","thyrotropin"],
      scope_population: 'ADULT',
    },
    direction: 'TARGET_BAND',
    cumulative_exposure_relevant: false,
    constants: {
      threshold_set: 'BIOSENSE_TSH_THRESHOLD_SET',
      score_gap_scale: 'TSH_SCORE_GAP_SCALE',
      significant_change_threshold: 'TSH_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'TSH_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'TSH_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'TSH_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'TSH_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'TSH_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/free-t4.json', FREE_T4_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'FREE_T4',
    display_name: 'Free T4',
    ingestion: {
      unit_canonical: 'ng/dL',
      conversions: {"ng/dL":1,"pmol/L":0.07770007770007771},
      aliases: ["Free T4","FT4","free thyroxine"],
      scope_population: 'ADULT',
    },
    direction: 'TARGET_BAND',
    cumulative_exposure_relevant: false,
    constants: {
      threshold_set: 'BIOSENSE_FREE_T4_THRESHOLD_SET',
      score_gap_scale: 'FREE_T4_SCORE_GAP_SCALE',
      significant_change_threshold: 'FREE_T4_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'FREE_T4_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'FREE_T4_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'FREE_T4_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'FREE_T4_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'FREE_T4_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/haemoglobin.json', HAEMOGLOBIN_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'HAEMOGLOBIN',
    display_name: 'Haemoglobin',
    ingestion: {
      unit_canonical: 'g/dL',
      conversions: {"g/dL":1,"g/L":0.1},
      aliases: ["Haemoglobin","Hemoglobin","Hb","Hgb"],
      scope_population: 'ADULT',
    },
    direction: 'TARGET_BAND',
    cumulative_exposure_relevant: false,
    constants: {
      threshold_set: 'BIOSENSE_HAEMOGLOBIN_THRESHOLD_SET',
      score_gap_scale: 'HAEMOGLOBIN_SCORE_GAP_SCALE',
      significant_change_threshold: 'HAEMOGLOBIN_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'HAEMOGLOBIN_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'HAEMOGLOBIN_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'HAEMOGLOBIN_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'HAEMOGLOBIN_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'HAEMOGLOBIN_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/wbc.json', WBC_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'WBC',
    display_name: 'White Blood Cell Count',
    ingestion: {
      unit_canonical: '×10⁹/L',
      conversions: {"×10⁹/L":1,"x10^9/L":1,"/µL":0.001},
      aliases: ["WBC","White cell count","Leukocytes"],
      scope_population: 'ADULT',
    },
    direction: 'TARGET_BAND',
    cumulative_exposure_relevant: false,
    constants: {
      threshold_set: 'BIOSENSE_WBC_THRESHOLD_SET',
      score_gap_scale: 'WBC_SCORE_GAP_SCALE',
      significant_change_threshold: 'WBC_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'WBC_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'WBC_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'WBC_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'WBC_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'WBC_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/ggt.json', GGT_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'GGT',
    display_name: 'GGT',
    ingestion: {
      unit_canonical: 'U/L',
      conversions: {"U/L":1,"IU/L":1},
      aliases: ["GGT","Gamma-GT","γ-GT"],
      scope_population: 'ADULT',
    },
    direction: 'LOWER_BETTER',
    cumulative_exposure_relevant: true,
    constants: {
      threshold_set: 'BIOSENSE_GGT_THRESHOLD_SET',
      score_gap_scale: 'GGT_SCORE_GAP_SCALE',
      significant_change_threshold: 'GGT_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'GGT_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'GGT_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'GGT_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'GGT_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'GGT_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/alp.json', ALP_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'ALP',
    display_name: 'Alkaline Phosphatase',
    ingestion: {
      unit_canonical: 'U/L',
      conversions: {"U/L":1,"IU/L":1},
      aliases: ["ALP","Alkaline Phosphatase"],
      scope_population: 'ADULT',
    },
    direction: 'TARGET_BAND',
    cumulative_exposure_relevant: false,
    constants: {
      threshold_set: 'BIOSENSE_ALP_THRESHOLD_SET',
      score_gap_scale: 'ALP_SCORE_GAP_SCALE',
      significant_change_threshold: 'ALP_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'ALP_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'ALP_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'ALP_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'ALP_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'ALP_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/bilirubin.json', BILIRUBIN_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'BILIRUBIN',
    display_name: 'Bilirubin',
    ingestion: {
      unit_canonical: 'mg/dL',
      conversions: {"mg/dL":1,"µmol/L":0.05847953216374269},
      aliases: ["Bilirubin","Total bilirubin"],
      scope_population: 'ADULT',
    },
    direction: 'LOWER_BETTER',
    cumulative_exposure_relevant: true,
    constants: {
      threshold_set: 'BIOSENSE_BILIRUBIN_THRESHOLD_SET',
      score_gap_scale: 'BILIRUBIN_SCORE_GAP_SCALE',
      significant_change_threshold: 'BILIRUBIN_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'BILIRUBIN_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'BILIRUBIN_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'BILIRUBIN_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'BILIRUBIN_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'BILIRUBIN_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

  registerClaimSource('csl-data/albumin.json', ALBUMIN_CLAIMS as never)
  registerBiomarkerConfig({
    analyte: 'ALBUMIN',
    display_name: 'Albumin',
    ingestion: {
      unit_canonical: 'g/dL',
      conversions: {"g/dL":1,"g/L":0.1},
      aliases: ["Albumin","Serum albumin"],
      scope_population: 'ADULT',
    },
    direction: 'HIGHER_BETTER',
    cumulative_exposure_relevant: false,
    constants: {
      threshold_set: 'BIOSENSE_ALBUMIN_THRESHOLD_SET',
      score_gap_scale: 'ALBUMIN_SCORE_GAP_SCALE',
      significant_change_threshold: 'ALBUMIN_SIGNIFICANT_CHANGE_THRESHOLD',
      acute_recovery_window: 'ALBUMIN_ACUTE_RECOVERY_WINDOW',
      lifestyle_gap_ceiling: 'ALBUMIN_LIFESTYLE_ADDRESSABLE_GAP_CEILING',
      low_investigation_threshold: 'ALBUMIN_LOW_INVESTIGATION_THRESHOLD',
      fh_pattern_threshold: 'ALBUMIN_FH_PATTERN_THRESHOLD',
      
    },
    recommendation_ladder: {
      large_gap: 'HIGH',
      lifestyle_addressable: 'MEDIUM',
      maintenance: 'LOW',
      low_investigation: 'MEDIUM',
    },
    recommendation_routing: {
      LIFESTYLE_DIETARY: 'SELF_CARE',
      LIFESTYLE_ACTIVITY: 'SELF_CARE',
      MONITOR: 'SELF_CARE',
      CLINICIAN_DISCUSSION: 'CLINICIAN',
    },
    lexicons: {
      drug_lexicon: 'BIOSENSE_LIPID_DRUG_LEXICON',
      prohibited_condition_lexicon: 'BIOSENSE_PROHIBITED_CONDITION_LEXICON',
    },
    recommendation_allowlist: [
      'LIFESTYLE_DIETARY',
      'LIFESTYLE_ACTIVITY',
      'MONITOR',
      'CLINICIAN_DISCUSSION',
    ],
    prohibited_recommendation_classes: [
      'PHARMACOLOGICAL_START',
      'PHARMACOLOGICAL_STOP',
      'PHARMACOLOGICAL_CHANGE',
      'THERAPY_UNNECESSARY',
    ],
    structural_nulls: {
      condition_named: null,
      numeric_risk_score: null,
      low_value_penalty: 0,
    },
    config_version: 'ALBUMIN_CONFIG@1.0.0',
  } satisfies BiomarkerConfig)

}
